import React, { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, ImagePlus, Info, LayoutGrid, List, Package, Pencil, Plus, SlidersHorizontal, X } from 'lucide-react';
import { Badge, Button, ErrorNote, Field, SelectField, TextAreaField } from '../../components/ui';
import { PageHeader, PageSkeleton, Pager, Panel, ProductImage, ResourceError, SearchInput, SellerEmpty } from '../../components/seller/ui';
import { StockAdjustModal } from '../../components/seller/StockAdjustModal';
import { refreshSeller, useSellerResource } from '../../context/SellerContext';
import { useToast } from '../../context/ToastContext';
import { api, errorMessage } from '../../lib/api';
import { useDebouncedValue } from '../../lib/hooks';
import { Link, navigate, useQueryParams } from '../../lib/router';
import { formatINR } from '../../lib/format';
import type { Product } from '../../types';
import type { Pagination } from '../../types/seller';

export const CATEGORIES = ['Grocery', 'Fruits & Vegetables', 'Dairy', 'Bakery', 'Snacks', 'Beverages', 'Personal Care', 'Household', 'Stationery', 'Pharmacy', 'Staples & Grains', 'Oils & Ghee', 'Frozen Foods'];
export const categoryOptions = CATEGORIES.map((value) => ({ value, label: value }));

export async function uploadSellerImage(file: File): Promise<string> {
  if (!['image/png', 'image/jpeg', 'image/webp'].includes(file.type)) throw new Error('Choose a PNG, JPEG or WEBP image.');
  if (file.size > 4 * 1024 * 1024) throw new Error('Image must be smaller than 4 MB.');
  const dataUrl = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(new Error('Could not read the image.')); reader.readAsDataURL(file); });
  return (await api.post<{ url: string }>('/api/seller/uploads', { dataUrl })).url;
}

export function SellerProductsPage() {
  const params = useQueryParams(); const toast = useToast();
  const [query, setQuery] = useState(params.get('query') ?? ''); const debounced = useDebouncedValue(query);
  const [filtersOpen, setFiltersOpen] = useState(false); const [category, setCategory] = useState(''); const [stock, setStock] = useState(''); const [published, setPublished] = useState(''); const [availability, setAvailability] = useState(''); const [minPrice, setMinPrice] = useState(''); const [maxPrice, setMaxPrice] = useState('');
  const [page, setPage] = useState(1); const [view, setView] = useState('grid'); const [busy, setBusy] = useState<string | null>(null); const [adjusting, setAdjusting] = useState<Product | null>(null);
  const queryString = new URLSearchParams({ query: debounced, category, stock, published, availability, minPrice, maxPrice, page: String(page), pageSize: '12' }).toString();
  const resource = useSellerResource(() => api.get<{ products: Product[]; categories: { category: string }[]; pagination: Pagination }>(`/api/seller/products?${queryString}`), [queryString]);
  useEffect(() => setPage(1), [debounced, category, stock, published, availability, minPrice, maxPrice]);
  const toggle = async (p: Product) => {
    setBusy(p.id);
    try { const result = await api.put<{ product: Product }>(`/api/seller/products/${p.id}`, { isPublished: p.is_published !== 1, expectedUpdatedAt: p.updated_at }); refreshSeller(); toast.push({ title: result.product.is_published ? 'Product published' : 'Product unpublished', tone: 'success' }); }
    catch (error) { toast.push({ title: 'Could not update product', description: errorMessage(error), tone: 'error' }); } finally { setBusy(null); }
  };
  const filterCount = [category, stock, published, availability, minPrice, maxPrice].filter(Boolean).length;
  return <div><PageHeader title="Products" subtitle="Everything your neighbourhood comes to you for." action={<Button onClick={() => navigate('/seller/products/new')}><Plus size={16} />Add product</Button>} />
    <div className="seller-filter-bar"><SearchInput value={query} onChange={setQuery} placeholder="Search products or SKU…" label="Search products" /><Button variant="secondary" onClick={() => setFiltersOpen((v) => !v)} aria-expanded={filtersOpen}><SlidersHorizontal size={14} />Filters{filterCount ? ` (${filterCount})` : ''}</Button><div className="seller-view-switch" role="group" aria-label="Product view"><button className={view === 'grid' ? 'active' : ''} onClick={() => setView('grid')} aria-label="Grid view" aria-pressed={view === 'grid'}><LayoutGrid size={15} /></button><button className={view === 'list' ? 'active' : ''} onClick={() => setView('list')} aria-label="List view" aria-pressed={view === 'list'}><List size={16} /></button></div></div>
    {filtersOpen && <div className="seller-filter-fields"><SelectField label="Category" value={category} onChange={(e) => setCategory(e.target.value)} options={[{ value: '', label: 'All categories' }, ...categoryOptions]} /><SelectField label="Stock" value={stock} onChange={(e) => setStock(e.target.value)} options={[{ value: '', label: 'All stock levels' }, { value: 'healthy', label: 'Healthy stock' }, { value: 'low', label: 'Low stock' }, { value: 'out', label: 'Out of stock' }]} /><SelectField label="Published" value={published} onChange={(e) => setPublished(e.target.value)} options={[{ value: '', label: 'All publishing states' }, { value: 'true', label: 'Published' }, { value: 'false', label: 'Unpublished' }]} /><SelectField label="Availability" value={availability} onChange={(e) => setAvailability(e.target.value)} options={[{ value: '', label: 'Any availability' }, { value: 'available', label: 'Available' }, { value: 'unavailable', label: 'Unavailable' }, { value: 'temporary', label: 'Temporarily unavailable' }]} /><Field label="Minimum price (₹)" type="number" min={0} value={minPrice} onChange={(e) => setMinPrice(e.target.value)} placeholder="Any" /><Field label="Maximum price (₹)" type="number" min={0} value={maxPrice} onChange={(e) => setMaxPrice(e.target.value)} placeholder="Any" /><Button variant="ghost" onClick={() => { setCategory(''); setStock(''); setPublished(''); setAvailability(''); setMinPrice(''); setMaxPrice(''); }}>Clear filters</Button></div>}
    <ResourceError error={resource.error} onRetry={resource.reload} />
    {resource.loading && !resource.data ? <PageSkeleton /> : !resource.data?.products?.length ? <Panel><SellerEmpty title={debounced || filterCount ? 'No matching products' : 'Your store has no products yet'} description={debounced || filterCount ? 'Try another search or change your filters.' : 'A great local store starts with its first listing. Add a product and make it discoverable.'} icon={<Package size={26} />} action={!debounced && !filterCount ? <Button onClick={() => navigate('/seller/products/new')}><Plus size={14} />Add your first product</Button> : undefined} /></Panel> : <div className={view === 'grid' ? 'seller-catalog-grid' : 'seller-catalog-list'}>{resource.data.products.map((p) => <article className="seller-product-card" key={p.id}><ProductImage src={p.image} name={p.name} /><div className="seller-product-card-body"><small>{p.category}</small><h2><Link to={`/seller/products/${p.id}`}>{p.name}</Link></h2><div className="seller-product-pricing"><strong>{formatINR(p.price)}</strong>{p.mrp && p.mrp > p.price ? <del>{formatINR(p.mrp)}</del> : null}</div><p className="seller-product-stock">{p.sellable ?? 0} available{p.reserved_quantity ? ` · ${p.reserved_quantity} reserved` : ''}</p><div className="flex flex-wrap gap-1.5"><Badge tone={p.is_published ? 'success' : 'neutral'}>{p.is_published ? '● Published' : 'Unpublished'}</Badge>{!p.sellable ? <Badge tone="danger">Out of stock</Badge> : p.sellable <= (p.low_stock_threshold ?? 5) ? <Badge tone="warning">Low stock</Badge> : null}{p.availability !== 'available' && p.availability && <Badge tone="neutral">{p.availability === 'temporary' ? 'Temporarily unavailable' : 'Unavailable'}</Badge>}</div></div><div className="seller-product-card-actions"><Button variant="secondary" size="sm" onClick={() => navigate(`/seller/products/${p.id}`)}><Pencil size={11} />Edit</Button><Button variant="secondary" size="sm" onClick={() => setAdjusting(p)}>Stock</Button><Button variant="ghost" size="sm" loading={busy === p.id} onClick={() => toggle(p)}>{p.is_published ? 'Unpublish' : 'Publish'}</Button></div></article>)}</div>}
    <Pager pagination={resource.data?.pagination} onPage={setPage} loading={resource.loading} /><StockAdjustModal product={adjusting} onClose={() => setAdjusting(null)} />
  </div>;
}

export function ProductEditorPage({ productId }: { productId?: string }) {
  const isEdit = Boolean(productId); const toast = useToast(); const initialized = useRef(false);
  const [form, setForm] = useState({ name: '', description: '', category: 'Grocery', brand: '', unit: '', sku: '', price: '', mrp: '', stock: '0', lowStockThreshold: '5', image: '', additionalImages: '', availability: 'available', isPublished: false });
  const [saving, setSaving] = useState(false); const [uploading, setUploading] = useState(false); const [error, setError] = useState<string | null>(null);
  const resource = useSellerResource(() => api.get<{ product: Product }>(`/api/seller/products/${productId}`), [productId], { enabled: isEdit });
  const original = useRef<Product | null>(null);
  useEffect(() => { initialized.current = false; original.current = null; }, [productId]);
  useEffect(() => {
    const p = resource.data?.product; if (!p || initialized.current || p.id !== productId) return;
    initialized.current = true; original.current = p;
    setForm({ name: p.name, description: p.description ?? '', category: p.category, brand: p.brand ?? '', unit: p.unit ?? '', sku: p.sku ?? '', price: String(p.price), mrp: p.mrp ? String(p.mrp) : '', stock: String(p.stock_quantity ?? 0), lowStockThreshold: String(p.low_stock_threshold ?? 5), image: p.image ?? '', additionalImages: (p.additional_images ?? []).join('\n'), availability: p.availability ?? 'available', isPublished: p.is_published === 1 });
  }, [resource.data, productId]);
  const change = (key: keyof typeof form, value: string | boolean) => setForm((f) => ({ ...f, [key]: value }));
  const upload = async (file: File) => { setUploading(true); setError(null); try { change('image', await uploadSellerImage(file)); toast.push({ title: 'Image uploaded', tone: 'success' }); } catch (err) { setError(errorMessage(err)); } finally { setUploading(false); } };
  const save = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault(); if (uploading || saving || (isEdit && !original.current)) return;
    const publish = ((event.nativeEvent as SubmitEvent).submitter as HTMLButtonElement | null)?.value === 'publish' ? true : form.isPublished;
    const images = form.additionalImages.split('\n').map((s) => s.trim()).filter(Boolean);
    if (images.length > 5) { setError('Add at most five additional images.'); return; }
    setSaving(true); setError(null);
    const payload = { ...form, price: Number(form.price), mrp: form.mrp ? Number(form.mrp) : null, stock: Number(form.stock), lowStockThreshold: Number(form.lowStockThreshold), image: form.image || null, additionalImages: images, isPublished: publish, expectedVersion: original.current?.inventory_version, expectedUpdatedAt: original.current?.updated_at };
    try { const result = isEdit ? await api.put<{ message: string; note?: string }>(`/api/seller/products/${productId}`, payload) : await api.post<{ message: string }>('/api/seller/products', payload); toast.push({ title: result.message, description: 'note' in result ? String(result.note ?? '') : undefined, tone: 'success' }); refreshSeller(); navigate('/seller/products'); }
    catch (err) { setError(errorMessage(err)); } finally { setSaving(false); }
  };
  if (isEdit && resource.loading && !resource.data) return <PageSkeleton />;
  if (isEdit && resource.error && !resource.data) return <ResourceError error={resource.error} onRetry={resource.reload} />;
  return <div><PageHeader title={isEdit ? 'Edit product' : 'Add a product'} subtitle={isEdit ? 'Keep your catalogue fresh and your customers informed.' : 'Your next neighbourhood favourite starts here.'} action={<Button variant="secondary" onClick={() => navigate('/seller/products')}><ArrowLeft size={14} />Back to products</Button>} />
    <form onSubmit={save}><ResourceError error={resource.error} onRetry={resource.reload} />{error && <ErrorNote className="mb-5">{error}</ErrorNote>}<div className="seller-form-layout"><div className="seller-form-main">
      <Panel className="seller-form-section"><h2><Package />Basic information</h2><p>Tell your customers what makes this product worth picking up.</p><div className="seller-form-grid"><Field label="Product name" value={form.name} onChange={(e) => change('name', e.target.value)} required maxLength={120} placeholder="e.g. Amul Taaza Milk 1L" /><SelectField label="Category" value={form.category} onChange={(e) => change('category', e.target.value)} options={categoryOptions} /><Field label="Brand (optional)" value={form.brand} onChange={(e) => change('brand', e.target.value)} placeholder="e.g. Amul" maxLength={80} /><Field label="Unit / size" value={form.unit} onChange={(e) => change('unit', e.target.value)} placeholder="e.g. 1 litre" maxLength={40} /><div className="full"><TextAreaField label="Description" value={form.description} onChange={(e) => change('description', e.target.value)} rows={4} maxLength={600} placeholder="A short, helpful description of your product…" /></div></div></Panel>
      <Panel className="seller-form-section"><h2>Pricing</h2><p>Prices are in Indian rupees. Customers always see the server-verified price.</p><div className="seller-form-grid"><Field label="Selling price (₹)" type="number" step="0.01" min="0.5" max="1000000" required value={form.price} onChange={(e) => change('price', e.target.value)} placeholder="68.00" /><Field label="MRP / comparison price (₹, optional)" type="number" step="0.01" min={Number(form.price) || 0.5} value={form.mrp} onChange={(e) => change('mrp', e.target.value)} placeholder="Leave blank if not applicable" /></div></Panel>
      <Panel className="seller-form-section"><h2>Inventory</h2><p>Count physical units on the shelf. Reservation holds are handled separately.</p><div className="seller-form-grid"><Field label={isEdit ? 'Shelf stock' : 'Initial stock'} type="number" min={0} max={100000} step={1} required value={form.stock} onChange={(e) => change('stock', e.target.value)} /><Field label="Low-stock threshold" type="number" min={0} max={100000} step={1} required value={form.lowStockThreshold} onChange={(e) => change('lowStockThreshold', e.target.value)} hint="You'll be alerted at or below this quantity." /><div className="full"><Field label="SKU / internal product code (optional)" value={form.sku} onChange={(e) => change('sku', e.target.value)} maxLength={60} placeholder="e.g. MILK01" hint="Unique within your store." /></div></div>{original.current?.reserved_quantity ? <div className="seller-form-note"><Info />{original.current.reserved_quantity} units are held for confirmed reservations and cannot be removed.</div> : null}</Panel>
    </div><div className="seller-form-aside"><Panel className="seller-form-section"><h2>Product media</h2><p>A clear image helps neighbours recognise the right product.</p><div className="seller-upload-box">{form.image ? <ProductImage src={form.image} name={form.name || 'Product image preview'} /> : <ImagePlus size={29} strokeWidth={1.5} />}<label tabIndex={0} onKeyDown={(e) => { if (e.key === 'Enter' || e.key === ' ') (e.currentTarget.querySelector('input') as HTMLInputElement)?.click(); }}><ImagePlus size={14} />{uploading ? 'Uploading image…' : 'Choose an image'}<input type="file" aria-label="Upload product image" accept="image/png,image/jpeg,image/webp" disabled={uploading} onChange={(e) => { const file = e.target.files?.[0]; if (file) void upload(file); e.target.value = ''; }} /></label><small>PNG, JPEG or WEBP · up to 4 MB</small></div><div className="mt-4"><Field label="Image URL (optional)" value={form.image} onChange={(e) => change('image', e.target.value)} placeholder="https://… or /uploads/…" /></div><div className="mt-4"><TextAreaField label="Additional image URLs" rows={3} value={form.additionalImages} onChange={(e) => change('additionalImages', e.target.value)} hint="One per line, up to 5 images." /></div>{form.additionalImages && <div className="seller-media-extra">{form.additionalImages.split('\n').filter(Boolean).slice(0, 5).map((url, i) => <ProductImage key={i} src={url} name={`Additional product image ${i + 1}`} />)}</div>}</Panel>
      <Panel className="seller-form-section"><h2>Availability & publishing</h2><p>Decide how this listing appears to customers.</p><SelectField label="Availability" value={form.availability} onChange={(e) => change('availability', e.target.value)} options={[{ value: 'available', label: 'Available' }, { value: 'unavailable', label: 'Unavailable' }, { value: 'temporary', label: 'Temporarily unavailable' }]} /><label className="seller-checkbox-line"><input type="checkbox" checked={form.isPublished} onChange={(e) => change('isPublished', e.target.checked)} />Publish to customers</label><div className="seller-form-note"><Info />Unpublished products stay in your catalogue, but are hidden from customer discovery and checkout.</div></Panel>
    </div></div><div className="seller-form-actions"><Button variant="ghost" type="button" onClick={() => navigate('/seller/products')} disabled={saving}>Cancel</Button>{!isEdit && <Button type="submit" variant="secondary" loading={saving} disabled={uploading}>Save product</Button>}<Button type="submit" value={isEdit ? 'save' : 'publish'} loading={saving} disabled={uploading || (isEdit && !original.current)}>{isEdit ? 'Save changes' : 'Save & publish'}<ArrowRight size={14} /></Button></div></form>
  </div>;
}
