import React, { useEffect, useState } from 'react';
import { ArrowRight, Bell, CalendarClock, CheckCheck, CircleHelp, Clock3, Info, Package, PackageCheck, Send, ShieldCheck, ShoppingBag, Store, UserRound, Wallet } from 'lucide-react';
import { Badge, Button, ErrorNote, Field, SelectField, TextAreaField } from '../../components/ui';
import { PageHeader, PageSkeleton, Pager, Panel, PanelHeading, ResourceError, SearchInput, SellerEmpty, Tabs } from '../../components/seller/ui';
import { refreshSeller, useSellerResource } from '../../context/SellerContext';
import { useToast } from '../../context/ToastContext';
import { api, errorMessage } from '../../lib/api';
import { formatDateTime, relativeTime } from '../../lib/format';
import { Link, useQueryParams } from '../../lib/router';
import type { Pagination, SellerNotification } from '../../types/seller';

const ICONS: Record<string, typeof Bell> = { orders: ShoppingBag, inventory: Package, reservation: CalendarClock, stock_check: PackageCheck, platform: Store, payout: Wallet, security: ShieldCheck };
export function SellerNotificationsPage() {
  const [tab, setTab] = useState(''); const [category, setCategory] = useState(''); const [page, setPage] = useState(1); const [busy, setBusy] = useState<string | null>(null); const toast = useToast();
  const resource = useSellerResource(() => api.get<{ notifications: SellerNotification[]; unread: number; pagination: Pagination }>(`/api/seller/notifications?unread=${tab === 'unread'}&category=${category}&page=${page}&pageSize=15`), [tab, category, page], { pollMs: 25000 });
  useEffect(() => setPage(1), [tab, category]);
  const read = async (id?: string) => {
    setBusy(id ?? 'all');
    try { if (id) await api.put(`/api/seller/notifications/${id}`, {}); else { await api.post('/api/seller/notifications/read-all'); setPage(1); } refreshSeller(); }
    catch (err) { toast.push({ title: 'Could not mark notification read', description: errorMessage(err), tone: 'error' }); } finally { setBusy(null); }
  };
  return <div><PageHeader title="Notifications" subtitle="The little updates that keep your store running smoothly." action={<Button variant="secondary" disabled={!resource.data?.unread} loading={busy === 'all'} onClick={() => read()}><CheckCheck size={14} />Mark all as read</Button>} /><div className="seller-filter-bar"><div className="flex-1 min-w-0"><Tabs tabs={[{ value: '', label: 'All notifications' }, { value: 'unread', label: 'Unread', count: resource.data?.unread ?? 0 }]} value={tab} onChange={setTab} label="Notification read state" /></div><SelectField label="Category" value={category} onChange={(e) => setCategory(e.target.value)} options={[{ value: '', label: 'All categories' }, { value: 'orders', label: 'Orders' }, { value: 'inventory', label: 'Inventory' }, { value: 'reservation', label: 'Reservations' }, { value: 'stock_check', label: 'Stock checks' }, { value: 'platform', label: 'Platform' }, { value: 'payout', label: 'Payouts' }, { value: 'security', label: 'Security' }]} /></div><ResourceError error={resource.error} onRetry={resource.reload} />
    {resource.loading && !resource.data ? <PageSkeleton /> : <Panel>{resource.data?.notifications?.length ? <div className="seller-notification-list">{resource.data.notifications.map((n) => { const Icon = ICONS[n.category] ?? Bell; return <article key={n.id} className={`seller-notification ${n.read_at ? '' : 'unread'}`}><span className={`seller-icon-tile ${n.category === 'inventory' ? 'amber' : n.category === 'reservation' ? 'purple' : n.category === 'payout' ? 'green' : ''}`}><Icon /></span><div><h2>{n.title}{!n.read_at && <i aria-label="Unread" />}</h2><p>{n.body}</p><small>{formatDateTime(n.created_at)} · {relativeTime(n.created_at)}</small><div className="seller-notification-actions"><Link className="seller-text-link" to={n.href}>View details<ArrowRight size={11} /></Link>{!n.read_at && <Button size="sm" variant="ghost" loading={busy === n.id} onClick={() => read(n.id)}>Mark read</Button>}</div></div></article>; })}</div> : <SellerEmpty title={tab === 'unread' ? "You're all caught up" : 'No notifications yet'} description="New orders, requests, low-stock alerts and account updates will appear here." icon={<Bell size={26} />} />}</Panel>}<Pager pagination={resource.data?.pagination} onPage={setPage} loading={resource.loading} />
  </div>;
}

const HELP = [
  { title: 'Manage an order', category: 'Order help', icon: ShoppingBag, short: 'Accept, prepare, pack and mark ready.', body: 'Open Orders and accept the new order. Start preparing, mark it packed, then mark it ready for pickup. Each step is validated by the server. You cannot skip straight to delivery. Reject a new order only with a reason; its deducted stock will be returned.' },
  { title: 'Update your inventory', category: 'Products & stock', icon: Package, short: 'Keep shelf counts and stock alerts accurate.', body: 'In Inventory, choose Update or Restock. Increase adds units, Decrease removes units, and Set Stock sets the physical shelf count. Reservation holds are protected. If another checkout or reservation changed stock while you were editing, refresh the count before trying again.' },
  { title: 'Verify a pickup', category: 'Rider handover', icon: ShieldCheck, short: 'A secure handover to the right person.', body: 'For delivery, mark the order ready and wait for an assigned rider. Check their identity and verify the last four digits of their registered phone. Reveal the pickup code only when you are ready to hand over. Complete Pickup requires that verification and the correct code. The customer’s delivery code is never shown to you.' },
  { title: 'Reservations vs stock checks', category: 'Customer requests', icon: CalendarClock, short: 'Availability is not the same as a hold.', body: 'Confirming a stock request only confirms availability. Confirming a reservation actually holds inventory until expiry, rejection, cancellation or collection. Only mark a confirmed reservation fulfilled after the customer has collected it. Expired holds are released automatically when the server refreshes operations.' },
  { title: 'Sales & settlements', category: 'Payment help', icon: Wallet, short: 'Understand the figures behind your business.', body: 'Analytics uses actual order item values, excluding cancelled and rejected orders. Earnings shows completed item sales and genuine ledger adjustments. Cash on delivery and test mode are supported. Online capture, automatic settlement and email delivery providers are not connected. Test-mode orders do not capture real money.' },
  { title: 'Store & account settings', category: 'Your business', icon: Store, short: 'Visibility, hours and account security.', body: 'Save your store details, preview your storefront, then publish. Closing a store pauses checkout while keeping products visible; unpublishing removes it from discovery. Security lets you change your password and revoke sessions. Never share your password, payment secrets or recovery links in a support ticket.' },
];
interface Ticket { id: string; category: string; subject: string; message: string; status: string; created_at: string; order_id: string | null }
export function SellerSupportPage() {
  const params = useQueryParams(); const toast = useToast(); const [query, setQuery] = useState(''); const [page, setPage] = useState(1);
  const [form, setForm] = useState({ category: 'other', subject: '', message: '', orderId: params.get('orderId') ?? '' }); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const resource = useSellerResource(() => api.get<{ tickets: Ticket[]; pagination: Pagination }>(`/api/seller/support?page=${page}&pageSize=10`), [page]);
  const matches = HELP.filter((h) => `${h.title} ${h.short} ${h.body}`.toLowerCase().includes(query.toLowerCase()));
  const submit = async (e: React.FormEvent) => {
    e.preventDefault(); setSaving(true); setError(null);
    try { const result = await api.post<{ ticket: Ticket; message: string }>('/api/seller/support', form); setForm({ category: 'other', subject: '', message: '', orderId: '' }); setPage(1); resource.reload(); toast.push({ title: `Issue ${result.ticket.id.slice(-6).toUpperCase()} saved`, description: result.message, tone: 'success' }); }
    catch (err) { setError(errorMessage(err)); } finally { setSaving(false); }
  };
  return <div><PageHeader title="Help & support" subtitle="A little help, whenever your business needs it." /><div className="seller-support-intro"><span><CircleHelp size={25} strokeWidth={1.5} /></span><h2>How can we help you today?</h2><p>Find a quick answer or save an issue to your support queue.</p><SearchInput value={query} onChange={setQuery} placeholder="Search orders, inventory, payments…" label="Search help centre" /></div><div className="seller-help-grid">{matches.map((h) => <article key={h.title} className="seller-help-card"><span className="seller-icon-tile"><h.icon /></span><h3>{h.title}</h3><p>{h.short}</p><details><summary>Read guide</summary><p>{h.body}</p></details></article>)}</div>{!matches.length && <Panel className="mb-5"><SellerEmpty title="No help articles match" description="Try another keyword, or tell us about the issue below." icon={<CircleHelp size={26} />} /></Panel>}
    <div className="seller-detail-layout"><Panel className="seller-form-section"><h2><Send />Contact support / report an issue</h2><p>Your issue is stored securely in your account's support queue.</p><form onSubmit={submit}><div className="seller-form-grid"><SelectField label="Issue type" value={form.category} onChange={(e) => setForm((f) => ({ ...f, category: e.target.value }))} options={[{ value: 'order', label: 'Order problem' }, { value: 'payment', label: 'Payment / settlement problem' }, { value: 'store', label: 'Store problem' }, { value: 'account', label: 'Account problem' }, { value: 'other', label: 'Other issue' }]} /><Field label="Order ID (optional)" value={form.orderId} onChange={(e) => setForm((f) => ({ ...f, orderId: e.target.value }))} placeholder="ord_…" hint="Only an order from your own store." /><div className="full"><Field label="Subject" required minLength={5} maxLength={120} value={form.subject} onChange={(e) => setForm((f) => ({ ...f, subject: e.target.value }))} placeholder="A brief summary of the problem" /></div><div className="full"><TextAreaField label="Tell us what happened" required minLength={10} maxLength={2000} rows={5} value={form.message} onChange={(e) => setForm((f) => ({ ...f, message: e.target.value }))} placeholder="Include the steps you took and what you expected. Never include passwords or payment secrets." /></div></div>{error && <ErrorNote className="mt-4">{error}</ErrorNote>}<div className="seller-form-note"><Info />This saves a ticket; it does not start a live chat or send an email. No response time is promised.</div><div className="seller-form-actions"><Button type="submit" loading={saving}>Submit issue<Send size={13} /></Button></div></form></Panel><Panel><PanelHeading title="Your support queue" subtitle="Persisted issues, only visible to your account." /><ResourceError error={resource.error} onRetry={resource.reload} />{resource.loading && !resource.data ? <PageSkeleton /> : resource.data?.tickets?.length ? <div className="px-5 pb-5 space-y-4">{resource.data.tickets.map((t) => <article className="border-t border-slate-100 pt-4" key={t.id}><div className="flex items-center justify-between gap-2"><span className="text-[10px] text-slate-500">#{t.id.slice(-6).toUpperCase()}</span><Badge tone="warning">{t.status}</Badge></div><h3 className="mt-2 text-xs font-semibold text-slate-700">{t.subject}</h3><p className="mt-1 text-xs text-slate-500 whitespace-pre-wrap">{t.message}</p><small className="block mt-2 text-[10px] text-slate-500">{t.category} · {formatDateTime(t.created_at)}</small></article>)}<Pager pagination={resource.data.pagination} onPage={setPage} loading={resource.loading} /></div> : <SellerEmpty title="No issues reported" description="We hope it stays that way. Your submitted issues will appear here." icon={<CircleHelp size={25} />} />}</Panel></div>
  </div>;
}
