import React, { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, CalendarDays, Check, Clock3, Eye, EyeOff, Info, MapPin, Package, Phone, Search, ShieldCheck, ShoppingBag, SlidersHorizontal, Store, Truck, UserRound } from 'lucide-react';
import { Badge, Button, ErrorNote, Field, InfoNote, Modal, SelectField, TextAreaField } from '../../components/ui';
import { Avatar, PageHeader, PageSkeleton, Pager, Panel, PanelHeading, ProductImage, ResourceError, SearchInput, SellerEmpty, Tabs } from '../../components/seller/ui';
import { refreshSeller, useSellerResource } from '../../context/SellerContext';
import { useToast } from '../../context/ToastContext';
import { api, errorMessage } from '../../lib/api';
import { useDebouncedValue } from '../../lib/hooks';
import { Link, navigate, useQueryParams } from '../../lib/router';
import { formatDateTime, formatINR, formatTime, orderStatusMeta, relativeTime } from '../../lib/format';
import type { Order, OrderStatus } from '../../types';
import type { Pagination } from '../../types/seller';

const NEXT_ACTION: Partial<Record<OrderStatus, { next: string; label: string }>> = {
  placed: { next: 'accepted', label: 'Accept order' }, accepted: { next: 'preparing', label: 'Start preparing' },
  preparing: { next: 'packed', label: 'Mark packed' }, packed: { next: 'ready_for_pickup', label: 'Ready for pickup' },
};
function OrderActions({ order, onChanged }: { order: Order; onChanged?: (order: Order) => void }) {
  const toast = useToast(); const [busy, setBusy] = useState(false); const [rejectOpen, setRejectOpen] = useState(false); const [reason, setReason] = useState(''); const [error, setError] = useState<string | null>(null);
  const next = NEXT_ACTION[order.status];
  const change = async (target: string) => {
    if (target === 'rejected' && !reason.trim()) { setError('Add a short reason for the customer.'); return; }
    setBusy(true); setError(null);
    try { const result = await api.post<{ order: Order; message: string }>(`/api/seller/orders/${order.id}/status`, { status: target, expectedStatus: order.status, reason: target === 'rejected' ? reason.trim() : undefined }); onChanged?.(result.order); refreshSeller(); toast.push({ title: result.message, tone: 'success' }); setRejectOpen(false); setReason(''); }
    catch (err) { if (rejectOpen) setError(errorMessage(err)); else toast.push({ title: 'Could not update order', description: errorMessage(err), tone: 'error' }); } finally { setBusy(false); }
  };
  if (!next) return null;
  return <><Button size="sm" loading={busy} onClick={() => change(next.next)}>{next.label}<ArrowRight size={12} /></Button>{order.status === 'placed' && <Button size="sm" variant="ghost" className="text-red-700" disabled={busy} onClick={() => { setRejectOpen(true); setError(null); }}>Reject</Button>}<Modal open={rejectOpen} onClose={() => !busy && setRejectOpen(false)} title="Reject this order?" description="The customer will see your reason. Deducted stock is returned to your shelf and any rider job is cancelled." footer={<><Button variant="ghost" disabled={busy} onClick={() => setRejectOpen(false)}>Keep order</Button><Button variant="danger" loading={busy} onClick={() => change('rejected')}>Reject order</Button></>}><TextAreaField label="Reason for rejection" required maxLength={240} rows={3} value={reason} onChange={(e) => setReason(e.target.value)} placeholder="e.g. We can't fulfil one of the items today." />{error && <ErrorNote>{error}</ErrorNote>}</Modal></>;
}

export function SellerOrdersPage() {
  const params = useQueryParams(); const initial = params.get('status') ?? '';
  const [status, setStatus] = useState(initial === 'placed' ? 'new' : initial); const [query, setQuery] = useState(''); const [date, setDate] = useState(''); const [fulfillment, setFulfillment] = useState(''); const [minPrice, setMinPrice] = useState(''); const [maxPrice, setMaxPrice] = useState('');
  const [filters, setFilters] = useState(false); const [page, setPage] = useState(1); const debounced = useDebouncedValue(query);
  const qs = new URLSearchParams({ status, query: debounced, date, fulfillment, minPrice, maxPrice, page: String(page), pageSize: '15' }).toString();
  const resource = useSellerResource(() => api.get<{ orders: Order[]; counts: Partial<Record<OrderStatus, number>>; pagination: Pagination }>(`/api/seller/orders?${qs}`), [qs], { pollMs: 15000 });
  useEffect(() => setPage(1), [status, debounced, date, fulfillment, minPrice, maxPrice]);
  useEffect(() => { const s = params.get('status') ?? ''; setStatus(s === 'placed' ? 'new' : s); }, [params.toString()]);
  const c = resource.data?.counts ?? {}; const total = Object.values(c).reduce((sum, n) => sum + (n ?? 0), 0);
  return <div><PageHeader title="Orders" subtitle="From the first hello to the final handover. You're in control." action={<span className="seller-date-chip"><Clock3 size={13} />Refreshes every 15 seconds</span>} />
    <Tabs value={status} onChange={setStatus} label="Order status" tabs={[{ value: '', label: 'All orders', count: total }, { value: 'new', label: 'New', count: c.placed ?? 0 }, { value: 'preparing', label: 'Preparing', count: (c.accepted ?? 0) + (c.preparing ?? 0) + (c.packed ?? 0) }, { value: 'ready', label: 'Ready', count: c.ready_for_pickup ?? 0 }, { value: 'completed', label: 'Completed', count: c.delivered ?? 0 }, { value: 'cancelled', label: 'Cancelled', count: (c.cancelled ?? 0) + (c.rejected ?? 0) }]} />
    <div className="seller-filter-bar"><SearchInput value={query} onChange={setQuery} placeholder="Search order ID…" label="Search order ID" /><Button variant="secondary" onClick={() => setFilters((v) => !v)} aria-expanded={filters}><SlidersHorizontal size={14} />Filters{[date, fulfillment, minPrice, maxPrice].some(Boolean) ? ' applied' : ''}</Button></div>{filters && <div className="seller-filter-fields"><Field label="Order date (store local time)" type="date" value={date} onChange={(e) => setDate(e.target.value)} /><SelectField label="Fulfilment type" value={fulfillment} onChange={(e) => setFulfillment(e.target.value)} options={[{ value: '', label: 'Delivery & pickup' }, { value: 'delivery', label: 'Home delivery' }, { value: 'pickup', label: 'Store pickup' }]} /><Field label="Minimum order value (₹)" type="number" min={0} value={minPrice} onChange={(e) => setMinPrice(e.target.value)} placeholder="Any" /><Field label="Maximum order value (₹)" type="number" min={0} value={maxPrice} onChange={(e) => setMaxPrice(e.target.value)} placeholder="Any" /><Button variant="ghost" onClick={() => { setDate(''); setFulfillment(''); setMinPrice(''); setMaxPrice(''); }}>Clear filters</Button></div>}
    <ResourceError error={resource.error} onRetry={resource.reload} />{resource.loading && !resource.data ? <PageSkeleton /> : !resource.data?.orders?.length ? <Panel><SellerEmpty title="No orders in this view" description={query || date || fulfillment || minPrice || maxPrice ? 'Try clearing your filters or searching another order ID.' : 'New customer orders will appear here. Keep your store open and your shelves stocked.'} icon={<ShoppingBag size={26} />} /></Panel> : <div className="seller-order-list">{resource.data.orders.map((order) => {
      const meta = orderStatusMeta(order.status); const itemCount = order.items.reduce((n, item) => n + item.quantity, 0);
      return <article className="seller-order-card" key={order.id}><div className="seller-order-card-top"><div className="seller-order-card-title"><Avatar name={order.customer?.name ?? 'Customer'} /><div><h2><Link to={`/seller/orders/${order.id}`}>#{order.orderNumber}</Link></h2><p>{order.customer?.name} · {formatDateTime(order.createdAt)}</p></div></div><div className="seller-order-card-meta"><Badge tone={meta.tone}>{order.status === 'placed' ? 'New order' : meta.label}</Badge><span>{order.fulfillmentType === 'delivery' ? <Truck size={13} /> : <Store size={13} />}{order.fulfillmentType === 'delivery' ? 'Delivery' : 'Store pickup'}</span><span><Package size={13} />{itemCount} items</span></div><div className="seller-order-card-amount"><strong>{formatINR(order.total)}</strong><small>{formatINR(order.subtotal)} + {formatINR(order.deliveryFee)} delivery</small></div></div><div className="seller-order-card-bottom"><span>{meta.sellerHint || 'Status confirmed by the server.'}</span><div><Button variant="secondary" size="sm" onClick={() => navigate(`/seller/orders/${order.id}`)}>View order</Button><OrderActions order={order} /></div></div></article>;
    })}</div>}<Pager pagination={resource.data?.pagination} onPage={setPage} loading={resource.loading} />
  </div>;
}

const MILESTONES = [
  ['ORDER_PLACED', 'Order placed'], ['ORDER_ACCEPTED', 'Accepted'], ['ORDER_PREPARING', 'Preparing'], ['ORDER_PACKED', 'Packed'],
  ['ORDER_READY_FOR_PICKUP', 'Ready for pickup'], ['RIDER_ASSIGNED', 'Rider assigned'], ['PICKUP_VERIFIED', 'Picked up'], ['ORDER_OUT_FOR_DELIVERY', 'Out for delivery'], ['DELIVERY_COMPLETED', 'Delivered'],
];
function PickupPanel({ order, onChanged }: { order: Order; onChanged: (order: Order) => void }) {
  const [code, setCode] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const [modal, setModal] = useState<'rider' | 'pickup' | 'customer' | null>(null); const [input, setInput] = useState(''); const toast = useToast();
  useEffect(() => { setCode(null); setError(null); setModal(null); }, [order.id, order.status]);
  const reveal = async () => { if (code) { setCode(null); return; } setBusy(true); setError(null); try { setCode((await api.post<{ pickupCode: string }>(`/api/seller/orders/${order.id}/pickup-code`)).pickupCode); } catch (err) { setError(errorMessage(err)); } finally { setBusy(false); } };
  const submit = async () => {
    setBusy(true); setError(null);
    try { const path = modal === 'rider' ? 'verify-rider' : modal === 'customer' ? 'customer-pickup' : 'complete-pickup'; const result = await api.post<{ order: Order; message: string }>(`/api/seller/orders/${order.id}/${path}`, modal === 'rider' ? { phoneLast4: input } : { pickupCode: input }); onChanged(result.order); refreshSeller(); toast.push({ title: result.message, tone: 'success' }); setModal(null); setInput(''); }
    catch (err) { setError(errorMessage(err)); } finally { setBusy(false); }
  };
  const ready = order.status === 'ready_for_pickup';
  return <Panel className="seller-pickup"><h2><ShieldCheck size={17} className="text-blue-600" />{order.fulfillmentType === 'delivery' ? 'Rider pickup' : 'Customer pickup'}</h2>
    {!ready ? <p>{['out_for_delivery', 'delivered'].includes(order.status) ? 'Handover has been recorded. The seller cannot change delivery status.' : 'Finish packing, then mark this order ready for pickup.'}</p> : order.fulfillmentType === 'pickup' ? <><p>Ask the customer for the collection code shown in their order. This is not their delivery code.</p><Button size="sm" onClick={() => { setModal('customer'); setInput(''); setError(null); }}>Confirm customer collection</Button></> : <><p>Share this code only with the assigned rider.</p><div className="seller-code-reveal"><div><small>SECURE PICKUP CODE</small><strong>{code || 'PK-••••'}</strong></div><Button size="sm" variant="ghost" loading={busy && !modal} onClick={reveal}>{code ? <EyeOff size={14} /> : <Eye size={14} />}{code ? 'Hide' : 'Reveal'}</Button></div>{order.rider ? <div className="seller-detail-info !p-0"><div><Avatar name={order.rider.name} small /><span><strong>{order.rider.name}</strong>Assigned rider{order.riderVerified ? ' · Verified in person' : ' · Verify before handover'}</span></div></div> : <p>Waiting for a rider to claim this delivery.</p>}<div className="seller-pickup-actions"><Button size="sm" variant="secondary" disabled={!order.rider || Boolean(order.riderVerified)} onClick={() => { setModal('rider'); setInput(''); setError(null); }}><ShieldCheck size={13} />{order.riderVerified ? 'Rider verified' : 'Verify rider'}</Button><Button size="sm" disabled={!order.riderVerified} onClick={() => { setModal('pickup'); setInput(''); setError(null); }}>Complete pickup<ArrowRight size={12} /></Button></div></>}
    {error && !modal && <ErrorNote className="mt-3">{error}</ErrorNote>}<Modal open={Boolean(modal)} onClose={() => !busy && setModal(null)} title={modal === 'rider' ? 'Verify the assigned rider' : modal === 'customer' ? 'Confirm customer collection' : 'Complete rider pickup'} description={modal === 'rider' ? `Ask ${order.rider?.name ?? 'the assigned rider'} to confirm their registered mobile number. Check their identity in person.` : modal === 'customer' ? 'Enter the customer collection code and hand over the packed items. The server will record this as a completed store pickup.' : 'Confirm the assigned rider has received the packed order. This transfers delivery responsibility to the rider.'} footer={<><Button variant="ghost" disabled={busy} onClick={() => setModal(null)}>Cancel</Button><Button loading={busy} onClick={submit}>{modal === 'rider' ? 'Verify rider' : modal === 'customer' ? 'Confirm collection' : 'Confirm handover'}</Button></>}><Field label={modal === 'rider' ? 'Last 4 digits of rider phone' : modal === 'customer' ? 'Customer collection code' : 'Pickup code for this order'} value={input} onChange={(e) => setInput(e.target.value)} maxLength={modal === 'rider' ? 4 : 12} inputMode={modal === 'rider' ? 'numeric' : 'text'} placeholder={modal === 'rider' ? '0000' : 'PK-0000'} autoComplete="off" required />{error && <ErrorNote>{error}</ErrorNote>}</Modal>
  </Panel>;
}

export function SellerOrderDetailPage({ orderId }: { orderId: string }) {
  const resource = useSellerResource(() => api.get<{ order: Order }>(`/api/seller/orders/${orderId}`), [orderId], { pollMs: 15000 });
  if (resource.loading && !resource.data) return <PageSkeleton />;
  if (!resource.data) return <ResourceError error={resource.error} onRetry={resource.reload} />;
  const order = resource.data.order; const meta = orderStatusMeta(order.status); const itemCount = order.items.reduce((n, i) => n + i.quantity, 0);
  const onChanged = (o: Order) => resource.setData({ order: o });
  const terminal = order.status === 'cancelled' || order.status === 'rejected';
  const milestones = order.fulfillmentType === 'pickup' ? [...MILESTONES.slice(0, 5), ['CUSTOMER_PICKUP_COMPLETED', 'Collected by customer']] : MILESTONES;
  return <div><PageHeader title={`#${order.orderNumber}`} subtitle={<><span>{formatDateTime(order.createdAt)}</span><span>·</span><span>{itemCount} items</span><span>·</span><span>{order.fulfillmentType === 'delivery' ? 'Home delivery' : 'Store pickup'}</span></>} action={<Button variant="secondary" onClick={() => navigate('/seller/orders')}><ArrowLeft size={14} />All orders</Button>} /><ResourceError error={resource.error} onRetry={resource.reload} />
    <div className="mb-5 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 bg-white p-5"><div><Badge tone={meta.tone}>{meta.label}</Badge><p className="mt-2 text-xs text-slate-500">{meta.sellerHint || 'This status is confirmed by the persisted order workflow.'}</p></div><div className="flex flex-wrap gap-2"><OrderActions order={order} onChanged={onChanged} /></div></div>{terminal && order.cancelledReason && <InfoNote className="mb-5">{order.cancelledReason}</InfoNote>}
    <div className="seller-detail-layout"><div><Panel><PanelHeading title="Items to prepare" subtitle="Check each quantity before you pack." icon={<Package />} /><table className="seller-table seller-order-items"><caption className="sr-only">Products in this order</caption><thead><tr><th>Product</th><th className="numeric">Qty</th><th className="numeric">Price</th><th className="numeric">Total</th></tr></thead><tbody>{order.items.map((item) => <tr key={item.id}><td><div className="seller-table-product"><ProductImage src={item.image} name={item.name} /><strong>{item.name}</strong></div></td><td className="numeric">{item.quantity}</td><td className="numeric">{formatINR(item.unitPrice)}</td><td className="numeric">{formatINR(item.lineTotal)}</td></tr>)}</tbody></table><dl className="seller-financial-summary"><div><dt>Subtotal</dt><dd>{formatINR(order.subtotal)}</dd></div><div><dt>Delivery fee</dt><dd>{formatINR(order.deliveryFee)}</dd></div><div><dt>Total order value</dt><dd>{formatINR(order.total)}</dd></div></dl><div className="seller-earnings-note"><Info size={14} />{order.paymentMethod === 'test_mode' ? 'Test-mode order. No real payment is captured.' : 'Cash on delivery. Order value is not proof of an online payment.'}</div></Panel>
      <Panel><PanelHeading title="Customer & fulfilment" icon={<Truck />} /><div className="seller-detail-info"><div><UserRound /><span><strong>{order.customer?.name}</strong>Order customer</span></div>{order.customer?.phone && <div><Phone /><span><strong>{order.customer.phone}</strong>For order fulfilment only</span></div>}<div>{order.fulfillmentType === 'delivery' ? <Truck /> : <Store />}<span><strong>{order.fulfillmentType === 'delivery' ? 'Home delivery' : 'Customer pickup at store'}</strong>{order.rider ? `Assigned to ${order.rider.name}` : order.fulfillmentType === 'delivery' ? 'No rider assigned yet' : 'No rider required'}</span></div>{order.fulfillmentType === 'delivery' && order.address?.address && <div><MapPin /><span><strong>{order.address.name}</strong>{order.address.address}, {order.address.city} {order.address.pincode}</span></div>}</div></Panel>
    </div><div>{!terminal && <PickupPanel order={order} onChanged={onChanged} />}<Panel><PanelHeading title="Order timeline" subtitle="Recorded actions, not estimated progress." icon={<Clock3 />} /><ol className="seller-timeline">{milestones.map(([type, label]) => { let event = order.timeline.find((e) => e.event_type === type); if (type === 'ORDER_OUT_FOR_DELIVERY' && !event) event = order.timeline.find((e) => e.event_type === 'PICKUP_VERIFIED'); return <li key={type} className={event ? 'done' : ''}><span className="seller-timeline-dot">{event && <Check />}</span><div><strong>{label}</strong>{event ? <span>{formatDateTime(event.created_at)} · {event.actor_role}</span> : <span>{terminal ? 'Not reached' : 'Awaiting next step'}</span>}</div></li>; })}{terminal && <li className="done"><span className="seller-timeline-dot"><Check /></span><div><strong>{meta.label}</strong><span>{formatDateTime(order.updatedAt)}</span></div></li>}</ol>{order.timeline.some((e) => e.event_type === 'SELLER_RIDER_VERIFIED') && <div className="seller-earnings-note"><ShieldCheck size={13} />Assigned rider verification recorded in the handoff history.</div>}</Panel></div></div>
  </div>;
}
