import React, { useEffect, useState } from 'react';
import { ArrowRight, CalendarClock, Clock3, Info, PackageCheck, ShieldCheck } from 'lucide-react';
import { Badge, Button, ErrorNote, Field, Modal, TextAreaField } from '../../components/ui';
import { PageHeader, PageSkeleton, Pager, Panel, ProductImage, ResourceError, SellerEmpty, Tabs } from '../../components/seller/ui';
import { refreshSeller, useSellerResource } from '../../context/SellerContext';
import { useToast } from '../../context/ToastContext';
import { api, errorMessage } from '../../lib/api';
import { formatDateTime, RESERVATION_STATUS, statusMeta, STOCK_REQUEST_STATUS } from '../../lib/format';
import type { Reservation, StockRequest } from '../../types';
import type { Pagination } from '../../types/seller';

type RequestRow = Omit<StockRequest, 'status'> & Partial<Omit<Reservation, 'status'>> & { status: StockRequest['status'] | Reservation['status'] };
export function SellerRequestsPage({ kind = 'stock' }: { kind?: 'stock' | 'reservation' }) {
  const reservation = kind === 'reservation'; const toast = useToast(); const [status, setStatus] = useState('pending'); const [page, setPage] = useState(1);
  const [responding, setResponding] = useState<{ row: RequestRow; action: string } | null>(null); const [response, setResponse] = useState(''); const [holdHours, setHoldHours] = useState('24'); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const path = reservation ? 'reservations' : 'stock-requests'; const key = reservation ? 'reservations' : 'requests';
  const resource = useSellerResource(() => api.get<{ requests?: RequestRow[]; reservations?: RequestRow[]; counts: Record<string, number>; pagination: Pagination }>(`/api/seller/${path}?status=${status}&page=${page}&pageSize=12`), [kind, status, page], { pollMs: 20000 });
  useEffect(() => { setPage(1); }, [status]);
  useEffect(() => { setStatus('pending'); setPage(1); setResponding(null); }, [kind]);
  const rows = resource.data?.[key] ?? []; const c = resource.data?.counts ?? {};
  const choose = (row: RequestRow, action: string) => { setResponding({ row, action }); setResponse(''); setError(null); setHoldHours('24'); };
  const submit = async () => {
    if (!responding) return; setSaving(true); setError(null);
    try { const result = await api.put<{ message: string }>(`/api/seller/${path}/${responding.row.id}`, reservation ? { action: responding.action, sellerResponse: response || undefined, holdHours: Number(holdHours) } : { status: responding.action, sellerResponse: response || undefined }); refreshSeller(); setResponding(null); toast.push({ title: reservation ? 'Reservation updated' : 'Stock request answered', description: result.message, tone: 'success' }); }
    catch (err) { setError(errorMessage(err)); } finally { setSaving(false); }
  };
  const historyCount = Object.entries(c).filter(([s]) => s !== 'pending').reduce((sum, [, n]) => sum + n, 0);
  const tabs = reservation ? [{ value: 'pending', label: 'Pending', count: c.pending ?? 0 }, { value: 'confirmed', label: 'Confirmed', count: c.confirmed ?? 0 }, { value: 'fulfilled', label: 'Fulfilled', count: c.fulfilled ?? 0 }, { value: 'history', label: 'History', count: historyCount }] : [{ value: 'pending', label: 'Pending', count: c.pending ?? 0 }, { value: 'confirmed', label: 'Confirmed', count: c.confirmed ?? 0 }, { value: 'unavailable', label: 'Unavailable', count: c.unavailable ?? 0 }, { value: 'history', label: 'History', count: historyCount }];
  const title = reservation ? 'Reservations' : 'Stock requests';
  return <div><PageHeader title={title} subtitle={reservation ? 'A little certainty for your customers. Hold stock when you can.' : 'A quick answer makes a neighbour’s shopping a little easier.'} action={<span className="seller-date-chip"><Clock3 size={13} />Live customer requests</span>} /><div className="seller-request-banner">{reservation ? <ShieldCheck /> : <Info />}<span>{reservation ? 'Confirming a reservation holds real inventory until it expires, is rejected, or is fulfilled.' : <><b>Stock confirmed ≠ stock reserved.</b> Answering a stock check does not hold inventory.</>}</span></div><Tabs value={status} onChange={setStatus} label={`${title} status`} tabs={tabs} /><ResourceError error={resource.error} onRetry={resource.reload} />
    {resource.loading && !resource.data ? <PageSkeleton /> : !rows.length ? <Panel><SellerEmpty title={reservation ? status === 'pending' ? 'No reservation requests yet' : 'No reservations in this view' : status === 'pending' ? 'No pending stock requests' : 'No stock requests in this view'} description={reservation ? 'Customers can request a product hold from your storefront. Their requests will appear here.' : 'When a customer asks about a product, you can answer them right here.'} icon={reservation ? <CalendarClock size={26} /> : <PackageCheck size={26} />} /></Panel> : <div className="seller-request-grid">{rows.map((row) => {
      const meta = statusMeta(reservation ? RESERVATION_STATUS : STOCK_REQUEST_STATUS, row.status);
      return <article key={row.id} className="seller-request-card"><header><span>{reservation ? 'RESERVATION' : 'STOCK CHECK'} #{row.id.slice(-6).toUpperCase()}</span><Badge tone={meta.tone}>{!reservation && row.status === 'confirmed' ? 'Stock confirmed' : meta.label}</Badge></header><div className="seller-request-product"><ProductImage src={row.product_image} name={row.product_name} /><div><h2>{row.product_name} × {row.requested_quantity}</h2><p>{row.customer_name} · {formatDateTime(reservation ? row.requested_at : row.created_at)}</p></div></div><p>{row.stock_quantity ?? 0} on shelf · {row.sellable ?? 0} currently available</p>{row.note && <p className="seller-request-note">Customer note: “{row.note}”</p>}{row.seller_response && <p className="seller-request-note">Your response: {row.seller_response}</p>}{reservation && row.holds_stock ? <p><span className="text-emerald-700 font-medium">Stock reserved</span> · {row.requested_quantity} units held{row.expires_at ? ` until ${formatDateTime(row.expires_at)}` : ''}</p> : !reservation && row.status === 'confirmed' ? <p>Availability confirmed. No stock was reserved.</p> : null}{row.responded_at && <p>Responded {formatDateTime(row.responded_at)}</p>}
        <div className="seller-request-actions">{row.status === 'pending' ? <><Button variant="success" size="sm" onClick={() => choose(row, reservation ? 'confirm' : 'confirmed')}>{reservation ? 'Confirm & reserve stock' : 'Confirm available'}</Button><Button variant="secondary" size="sm" onClick={() => choose(row, reservation ? 'reject' : 'unavailable')}>{reservation ? 'Reject' : 'Mark unavailable'}</Button></> : reservation && row.status === 'confirmed' ? <><Button size="sm" onClick={() => choose(row, 'fulfil')}>Mark fulfilled<ArrowRight size={11} /></Button><Button variant="secondary" size="sm" onClick={() => choose(row, 'reject')}>Reject & release stock</Button></> : <span className="text-xs text-slate-500">{row.status === 'expired' ? 'Hold expired. Stock has been released.' : row.status === 'fulfilled' ? 'Collection recorded and held stock deducted.' : 'Saved to your request history.'}</span>}</div>
      </article>;
    })}</div>}<Pager pagination={resource.data?.pagination} onPage={setPage} loading={resource.loading} />
    <Modal open={Boolean(responding)} onClose={() => !saving && setResponding(null)} title={reservation ? responding?.action === 'confirm' ? 'Confirm & reserve stock' : responding?.action === 'fulfil' ? 'Mark reservation fulfilled' : 'Reject reservation' : responding?.action === 'confirmed' ? 'Confirm stock availability' : 'Mark stock unavailable'} description={responding ? `${responding.row.product_name} × ${responding.row.requested_quantity} for ${responding.row.customer_name}.` : ''} footer={<><Button variant="ghost" disabled={saving} onClick={() => setResponding(null)}>Cancel</Button><Button loading={saving} onClick={submit} variant={responding?.action === 'reject' || responding?.action === 'unavailable' ? 'danger' : 'primary'}>{reservation ? 'Confirm response' : 'Send response'}</Button></>}>
      {reservation && responding?.action === 'confirm' && <><Field label="Hold duration (hours)" type="number" min={1} max={168} value={holdHours} onChange={(e) => setHoldHours(e.target.value)} /><p className="text-xs text-slate-500">These units cannot be sold to another customer while the confirmed hold is active.</p></>}{reservation && responding?.action === 'fulfil' && <p className="text-xs text-slate-500">Only confirm after the customer has collected the items. The held units will be deducted from shelf stock.</p>}{!reservation && <p className="text-xs text-slate-500">This response informs the customer. It does not reserve or deduct stock.</p>}<TextAreaField label="Note to the customer (optional)" maxLength={300} rows={3} value={response} onChange={(e) => setResponse(e.target.value)} placeholder="Add a helpful note…" />{error && <ErrorNote>{error}</ErrorNote>}
    </Modal>
  </div>;
}
export function SellerStockRequestsPage() { return <SellerRequestsPage kind="stock" />; }
export function SellerReservationsPage() { return <SellerRequestsPage kind="reservation" />; }
