import React, { useEffect, useRef, useState } from 'react';
import { ArrowRight, BriefcaseBusiness, CheckCircle2, Clock3, ExternalLink, Eye, ImagePlus, Info, MapPin, Phone, ShieldCheck, Store as StoreIcon } from 'lucide-react';
import { Badge, Button, ErrorNote, Field, Modal, SelectField, TextAreaField } from '../../components/ui';
import { PageHeader, PageSkeleton, Panel, ProductImage, ResourceError, StoreStatus, Tabs } from '../../components/seller/ui';
import { refreshSeller, useSeller, useSellerResource } from '../../context/SellerContext';
import { useAuth } from '../../context/AuthContext';
import { useToast } from '../../context/ToastContext';
import { api, errorMessage } from '../../lib/api';
import { Link, navigate } from '../../lib/router';
import type { Store } from '../../types';
import { categoryOptions, uploadSellerImage } from './catalog';
import { StoreDetailPage } from '../public';

const DAYS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
const parseDays = (value?: string | null) => !value || value === 'Mon-Sun' ? DAYS : value === 'Mon-Sat' ? DAYS.slice(0, 6) : value === 'Tue-Sun' ? DAYS.slice(1) : value.split(',').map((s) => s.trim());
export function SellerStorePage({ section = 'profile' }: { section?: 'profile' | 'hours' | 'location' }) {
  const { user } = useAuth(); const toast = useToast(); const initialized = useRef(false);
  const resource = useSellerResource(() => api.get<{ store: Store | null }>('/api/seller/store'));
  const [form, setForm] = useState({ name: '', description: '', category: 'Grocery', address: '', city: '', state: '', pincode: '', contactPhone: user?.phone ?? '', contactEmail: '', opensAt: '08:00', closesAt: '22:00', latitude: '', longitude: '', image: '', logo: '', supportsDelivery: true, supportsPickup: true });
  const [days, setDays] = useState<string[]>(DAYS); const [saving, setSaving] = useState(false); const [uploading, setUploading] = useState(false); const [error, setError] = useState<string | null>(null); const [hideModal, setHideModal] = useState(false); const [visibilityBusy, setVisibilityBusy] = useState(false);
  useEffect(() => {
    const s = resource.data?.store; if (!s || initialized.current) return; initialized.current = true;
    setForm({ name: s.name, description: s.description ?? '', category: s.category, address: s.address, city: s.city, state: s.state, pincode: s.pincode, contactPhone: s.contact_phone ?? user?.phone ?? '', contactEmail: s.contact_email ?? '', opensAt: s.opens_at ?? '08:00', closesAt: s.closes_at ?? '22:00', latitude: s.latitude == null ? '' : String(s.latitude), longitude: s.longitude == null ? '' : String(s.longitude), image: s.image ?? '', logo: s.logo ?? '', supportsDelivery: s.supports_delivery !== 0, supportsPickup: s.supports_pickup !== 0 }); setDays(parseDays(s.operating_days));
  }, [resource.data, user?.phone]);
  const change = (key: keyof typeof form, value: string | boolean) => setForm((f) => ({ ...f, [key]: value }));
  const store = resource.data?.store;
  const save = async (event: React.FormEvent) => {
    event.preventDefault(); if (!days.length) { setError('Select at least one operating day.'); return; } setSaving(true); setError(null);
    try { const result = await api.post<{ store: Store; message: string }>('/api/seller/store', { ...form, operatingDays: DAYS.filter((d) => days.includes(d)).join(','), latitude: form.latitude ? Number(form.latitude) : null, longitude: form.longitude ? Number(form.longitude) : null, ...(!store ? { status: 'inactive' } : {}) }); initialized.current = true; resource.setData({ store: result.store }); refreshSeller(); toast.push({ title: result.message, tone: 'success' }); }
    catch (err) { setError(errorMessage(err)); } finally { setSaving(false); }
  };
  const upload = async (file: File, target: 'image' | 'logo') => { setUploading(true); setError(null); try { change(target, await uploadSellerImage(file)); } catch (err) { setError(errorMessage(err)); } finally { setUploading(false); } };
  const publish = async (value: boolean) => {
    setVisibilityBusy(true); setError(null);
    try { const result = await api.post<{ store: Store; message: string }>(`/api/seller/store/${value ? 'publish' : 'unpublish'}`); resource.setData({ store: result.store }); refreshSeller(); setHideModal(false); toast.push({ title: result.message, tone: 'success' }); }
    catch (err) { setError(errorMessage(err)); } finally { setVisibilityBusy(false); }
  };
  const changeStatus = async (status: string) => {
    setVisibilityBusy(true);
    try { const result = await api.post<{ store: Store; message: string }>('/api/seller/store/status', { status }); resource.setData({ store: result.store }); refreshSeller(); toast.push({ title: result.message, tone: 'success' }); }
    catch (err) { setError(errorMessage(err)); } finally { setVisibilityBusy(false); }
  };
  if (resource.loading && !resource.data) return <PageSkeleton />;
  const all = section === 'profile' || !store;
  return <div><PageHeader title={!store ? 'Create your store' : section === 'hours' ? 'Store hours' : section === 'location' ? 'Store location' : 'My store'} subtitle="Your place in the neighbourhood. Make it feel like you." action={store ? <Button variant="secondary" onClick={() => navigate('/seller/store/preview')}><Eye size={14} />Preview store</Button> : undefined} />
    {store && <Tabs value={section} onChange={(s) => navigate(s === 'profile' ? '/seller/store' : `/seller/store/${s}`)} label="Store sections" tabs={[{ value: 'profile', label: 'Store profile' }, { value: 'hours', label: 'Opening hours' }, { value: 'location', label: 'Location' }]} />}<ResourceError error={resource.error} onRetry={resource.reload} />{error && <ErrorNote className="mb-5">{error}</ErrorNote>}
    <form onSubmit={save}><div className="seller-form-layout"><div className="seller-form-main">
      {all && <><Panel className="seller-form-section"><h2><StoreIcon />Store identity</h2><p>A familiar name and a friendly introduction go a long way.</p><div className="seller-form-grid"><Field label="Store name" required minLength={3} maxLength={80} value={form.name} onChange={(e) => change('name', e.target.value)} placeholder="e.g. Dwarka Fresh Mart" /><SelectField label="Store category" value={form.category} onChange={(e) => change('category', e.target.value)} options={categoryOptions} /><div className="full"><TextAreaField label="Store description" maxLength={600} rows={4} value={form.description} onChange={(e) => change('description', e.target.value)} placeholder="Tell neighbours what they'll find at your store…" /></div></div></Panel><Panel className="seller-form-section"><h2><Phone />Contact information</h2><p>Public store contact details for fulfilment and customer enquiries.</p><div className="seller-form-grid"><Field label="Store phone" type="tel" value={form.contactPhone} onChange={(e) => change('contactPhone', e.target.value)} placeholder="+91 98112 34567" /><Field label="Store email (optional)" type="email" value={form.contactEmail} onChange={(e) => change('contactEmail', e.target.value)} placeholder="hello@yourstore.com" /></div></Panel></>}
      {(all || section === 'location') && <Panel className="seller-form-section"><h2><MapPin />Location</h2><p>Help nearby customers find you. Only your store address is public.</p><div className="seller-form-grid"><div className="full"><Field label="Store address" required minLength={5} maxLength={240} value={form.address} onChange={(e) => change('address', e.target.value)} placeholder="Shop number, market, street, sector…" /></div><Field label="City" required value={form.city} onChange={(e) => change('city', e.target.value)} placeholder="New Delhi" /><Field label="State" required value={form.state} onChange={(e) => change('state', e.target.value)} placeholder="Delhi" /><Field label="Pincode" required inputMode="numeric" pattern="[0-9]{4,10}" value={form.pincode} onChange={(e) => change('pincode', e.target.value)} placeholder="110078" /><span /><Field label="Latitude (optional)" type="number" step="any" min={-90} max={90} value={form.latitude} onChange={(e) => change('latitude', e.target.value)} placeholder="28.5921" /><Field label="Longitude (optional)" type="number" step="any" min={-180} max={180} value={form.longitude} onChange={(e) => change('longitude', e.target.value)} placeholder="77.0460" /></div>{form.latitude && form.longitude && <a className="seller-text-link mt-4" href={`https://www.openstreetmap.org/?mlat=${encodeURIComponent(form.latitude)}&mlon=${encodeURIComponent(form.longitude)}#map=17/${encodeURIComponent(form.latitude)}/${encodeURIComponent(form.longitude)}`} target="_blank" rel="noopener noreferrer">View map location<ExternalLink size={12} /></a>}<div className="seller-form-note"><Info />Coordinates support distance-based discovery. Delivery fees currently follow the platform's flat-fee rules, not an estimated distance.</div></Panel>}
      {(all || section === 'hours') && <Panel className="seller-form-section"><h2><Clock3 />Operating hours</h2><p>Your usual schedule. Use Open / Close to pause new orders whenever you need.</p><div className="seller-form-grid"><Field label="Opening time" type="time" required value={form.opensAt} onChange={(e) => change('opensAt', e.target.value)} /><Field label="Closing time" type="time" required value={form.closesAt} onChange={(e) => change('closesAt', e.target.value)} /><fieldset className="full"><legend className="mb-2 text-xs text-slate-600">Operating days</legend><div className="seller-days">{DAYS.map((d) => <button key={d} type="button" className={days.includes(d) ? 'active' : ''} aria-pressed={days.includes(d)} onClick={() => setDays((current) => current.includes(d) ? current.filter((v) => v !== d) : [...current, d])}>{d}</button>)}</div></fieldset></div><div className="mt-5 space-y-3"><label className="seller-checkbox-line"><input type="checkbox" checked={form.supportsDelivery} onChange={(e) => change('supportsDelivery', e.target.checked)} />Offer home delivery</label><label className="seller-checkbox-line"><input type="checkbox" checked={form.supportsPickup} onChange={(e) => change('supportsPickup', e.target.checked)} />Offer customer pickup at store</label></div></Panel>}
    </div><div className="seller-form-aside">{all && <Panel className="seller-form-section"><h2>Store photos</h2><p>Let customers recognise your shop before they arrive.</p><div className="seller-upload-box">{form.image ? <ProductImage src={form.image} name="Store cover image" /> : <ImagePlus size={29} />}<label><ImagePlus size={13} />{uploading ? 'Uploading…' : 'Upload cover image'}<input type="file" accept="image/png,image/jpeg,image/webp" aria-label="Upload store cover image" disabled={uploading} onChange={(e) => { const file = e.target.files?.[0]; if (file) void upload(file, 'image'); e.target.value = ''; }} /></label><small>PNG, JPEG or WEBP · up to 4 MB</small></div><div className="mt-4"><Field label="Cover image URL" value={form.image} onChange={(e) => change('image', e.target.value)} placeholder="/uploads/… or https://…" /></div><div className="mt-4"><Field label="Store logo URL (optional)" value={form.logo} onChange={(e) => change('logo', e.target.value)} /></div><label className="seller-text-link mt-3"><ImagePlus size={12} />Upload logo<input type="file" className="sr-only" aria-label="Upload store logo" accept="image/png,image/jpeg,image/webp" disabled={uploading} onChange={(e) => { const file = e.target.files?.[0]; if (file) void upload(file, 'logo'); e.target.value = ''; }} /></label></Panel>}
      <Panel className="seller-form-section"><h2><Eye />Store visibility</h2><p>Go live when your store is ready. Publishing is separate from opening or closing.</p>{store ? <><Badge tone={store.is_published ? 'success' : 'neutral'}>{store.is_published ? '● Published' : 'Unpublished'}</Badge><div className="seller-store-visibility"><div><strong>{store.is_published ? 'Visible to neighbours' : 'Not in customer discovery'}</strong><p>{store.is_published ? 'Customers can browse your published products.' : 'Preview and prepare before you publish.'}</p></div></div><Button type="button" className="mt-4 w-full" variant={store.is_published ? 'secondary' : 'primary'} loading={visibilityBusy} onClick={() => store.is_published ? setHideModal(true) : publish(true)}>{store.is_published ? 'Unpublish store' : 'Publish store'}<ArrowRight size={13} /></Button><div className="mt-5 border-t border-slate-100 pt-4"><StoreStatus store={store} /><div className="mt-3 flex flex-wrap gap-2"><Button type="button" size="sm" variant="secondary" disabled={visibilityBusy || !store.is_published} onClick={() => changeStatus(store.status === 'open' && !store.temporarily_unavailable ? 'closed' : 'open')}>{store.status === 'open' && !store.temporarily_unavailable ? 'Close store' : 'Open store'}</Button><Button type="button" size="sm" variant="ghost" disabled={visibilityBusy} onClick={() => changeStatus('temporary')}>Pause temporarily</Button></div></div></> : <div className="seller-form-note"><Info />Your new store will be saved as a draft. Add your products, preview your storefront, then publish.</div>}</Panel>
    </div></div><div className="seller-form-actions"><Button type="submit" loading={saving} disabled={uploading || visibilityBusy}>{store ? 'Save store details' : 'Create store'}<ArrowRight size={14} /></Button></div></form><Modal open={hideModal} onClose={() => !visibilityBusy && setHideModal(false)} title="Unpublish your store?" description="Your store and products will disappear from customer discovery. Existing orders, requests and inventory stay in your workspace." footer={<><Button variant="ghost" disabled={visibilityBusy} onClick={() => setHideModal(false)}>Keep published</Button><Button variant="danger" loading={visibilityBusy} onClick={() => publish(false)}>Unpublish store</Button></>}><p className="text-xs text-slate-500">You can publish again at any time. Closing temporarily is a better option for a short break.</p></Modal>
  </div>;
}

export function SellerStorePreviewPage() {
  const resource = useSeller(); const store = resource.data?.store;
  if (!store) return <div><PageHeader title="Store preview" /><Panel className="p-6"><p className="text-sm text-slate-500">Create a store before previewing it.</p><Button className="mt-4" onClick={() => navigate('/seller/store')}>Create store</Button></Panel></div>;
  return <div><PageHeader title="Store preview" subtitle="The same storefront and persisted catalogue your customers see." action={<Button variant="secondary" onClick={() => navigate('/seller/store')}>Back to my store</Button>} /><div className="seller-request-banner"><Eye /><span>Seller preview · {store.is_published ? 'Your store is published.' : 'Your store is still a draft.'} Shopping is disabled in preview.</span></div><StoreDetailPage storeId={store.id} preview /></div>;
}

interface Business { legal_name: string; owner_name: string; phone: string | null; email: string | null; category: string | null; address: string | null; business_identifier: string | null; support_contact: string | null }
export function SellerBusinessPage() {
  const { user } = useAuth(); const toast = useToast(); const initialized = useRef(false);
  const resource = useSellerResource(() => api.get<{ business: Business | null }>('/api/seller/business'));
  const [form, setForm] = useState({ legalName: '', ownerName: user?.name ?? '', phone: user?.phone ?? '', email: user?.email ?? '', category: 'Grocery', address: '', businessIdentifier: '', supportContact: '' });
  const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { const b = resource.data?.business; if (!b || initialized.current) return; initialized.current = true; setForm({ legalName: b.legal_name, ownerName: b.owner_name, phone: b.phone ?? '', email: b.email ?? '', category: b.category ?? 'Grocery', address: b.address ?? '', businessIdentifier: b.business_identifier ?? '', supportContact: b.support_contact ?? '' }); }, [resource.data]);
  const change = (key: keyof typeof form, value: string) => setForm((f) => ({ ...f, [key]: value }));
  const save = async (e: React.FormEvent) => { e.preventDefault(); setSaving(true); setError(null); try { const result = await api.put<{ message: string }>('/api/seller/business', form); refreshSeller(); toast.push({ title: result.message, tone: 'success' }); } catch (err) { setError(errorMessage(err)); } finally { setSaving(false); } };
  if (resource.loading && !resource.data) return <PageSkeleton />;
  return <div className="seller-form-limit"><PageHeader title="Business profile" subtitle="The details behind your neighbourhood business." /><div className="seller-request-banner"><ShieldCheck /><span>Private to your seller account. Business identifiers are never shown on your public storefront.</span></div><ResourceError error={resource.error} onRetry={resource.reload} /><Panel className="seller-form-section"><h2><BriefcaseBusiness />Business information</h2><p>Keep your legal and contact information up to date.</p><form onSubmit={save}>{error && <ErrorNote className="mb-4">{error}</ErrorNote>}<div className="seller-form-grid"><Field label="Legal / business name" required value={form.legalName} onChange={(e) => change('legalName', e.target.value)} maxLength={120} /><Field label="Owner name" required value={form.ownerName} onChange={(e) => change('ownerName', e.target.value)} maxLength={80} /><Field label="Business phone" type="tel" value={form.phone} onChange={(e) => change('phone', e.target.value)} /><Field label="Business email" type="email" value={form.email} onChange={(e) => change('email', e.target.value)} /><SelectField label="Business category" value={form.category} onChange={(e) => change('category', e.target.value)} options={categoryOptions} /><Field label="Business identifier (optional)" value={form.businessIdentifier} onChange={(e) => change('businessIdentifier', e.target.value)} maxLength={100} hint="Stored privately. Saving does not imply verification." /><div className="full"><TextAreaField label="Business address" rows={3} value={form.address} onChange={(e) => change('address', e.target.value)} maxLength={240} /></div><div className="full"><Field label="Support contact (optional)" value={form.supportContact} onChange={(e) => change('supportContact', e.target.value)} maxLength={120} /></div></div><div className="seller-form-actions"><Button type="submit" loading={saving}>Save business profile</Button></div></form></Panel></div>;
}
